#LOGGING
logging:
    config: classpath:config/logback.xml
server:
    port: 8080
#文件上传配置
multipart:
    enabled: true
    maxFileSize: 100Mb
    maxRequestSize: 100Mb
    location: ./upload
#spring config
spring:
    application:
        name: ${app.name}
        version: ${app.version}
#    datasource:  #使用hsweb动态数据源无需配置此项
#        name: core
#        url: ${jdbc.url}
#        username: ${jdbc.username}
#        password: ${jdbc.password}
#        type: com.alibaba.druid.pool.DruidDataSource
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
    freemarker :
        suffix : .ftl
        request-context-attribute : request
        expose-request-attributes : true
    mvc:
        favicon:
            enabled: false
# MyBatis
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
    config: classpath:config/mybatis-config.xml
hsweb:
    dynamic-datasource: #动态数据源配置
          url: jdbc:h2:file:./data/h2db;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:
    access-logger: on #开启访问日志