#LOGGING
logging:
    config: classpath:config/logback.xml
server:
    port: 8080
#文件上传配置
multipart:
    enabled: true
    maxFileSize: 100Mb
    maxRequestSize: 100Mb
    location: ./upload
#spring config
spring:
    freemarker :
        suffix : .ftl
        request-context-attribute : request
        expose-request-attributes : true
    mvc:
        favicon:
            enabled: false
    aop:
      auto: true
# MyBatis
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
    config: classpath:config/mybatis-config.xml
#    dynamic-datasource: true  #启用mybatis动态数据源
hsweb:
    app:
      name: hsweb demo
      version: 1.0
      comment: 演示项目
    dynamic-datasource: #动态数据源配置
          url: jdbc:h2:file:./data/h2db;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:
          icatch:
            max-actives: 100
            output-dir: ./data/atomikos
            log_base_dir: ./data/atomikos
            default-jta-timeout: 300000
    access-logger: on #开启访问日志